updated

diff --git a/.github/workflows/solar-system.yml b/.github/workflows/solar-system.yml
--- a/.github/workflows/solar-system.yml
+++ b/.github/workflows/solar-system.yml
@@ -51,7 +51,7 @@ jobs:
             uses: actions/upload-artifact@v4
             with:
               name: coverage-results
-              path: coverage
+              path: coverage/
               retention-days: 3
     report-s3:
       name: upload reports to aws
@@ -67,9 +67,10 @@ jobs:
 
         - name: Merge test files
           run: |
-              mkdir reports-${{ github.sha }}/
-              mv coverage/lcov.info reports-${{ github.sha }}/
-              ls -ltr reports-${{ github.sha }}/
+               mkdir reports-${{ github.sha }}/
+               mv unit-test-results.xml reports-${{ github.sha }}/ || echo "unit-test-results.xml not found"
+               mv coverage/lcov.info reports-${{ github.sha }}/ || echo "lcov.info not found"
+               ls -ltr reports-${{ github.sha }}/
         - name: Uploading to aws
           run: echo "Uploadingggggg"
     docker:
